# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the mainline branch
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install root dependencies
      - name: Root Install
        run: npm ci
      
      # Install web dependencies
      - name: Web Install
        run: npm ci
        working-directory: ./web
        
      # Install studio dependencies
      - name: Studio Install
        run: npm ci
        working-directory: ./studio

      # Runs a single command using the runners shell
      - name: ESLint
        run: npm run lint
